### ISSUE TITLE
Add a restore actions dependent on change tracking

### ISSUE THREAD

**Issue by rgraff** [ash-project/ash_paper_trail#12]
RFC: For snapshot change tracking, add a restore action to the source resource to restore it to the state of a version.  For resources with snapshot change tracking this would undo the changes made.

Normal validations and policies would apply.

**Comment by rgraff** [comment]
Change tracking would require a full diff:

Proposed structure for an update change with snapshot:

```javascript
{
   subject: { from: "subject", to: "new subject" },
   body: { unchanged: "body" }
   embedded_author: {
      first_name: { unchanged: "Jane" },
      last_name: { from: "Doh", to: "Doe" }
   } 
   embedded_tags: {
      "tag-3": {
         op: "create", 
         changes: { tag: { to: "ash" }   }
         index: { to: 0 }
      },
      "tag-1": {
         op: "update",
         changes: { tag: { unchanged: "phoenix" } },
         index: { from: 0, to: 1 }
      },
      "tag-2": {
         op: "destroy",
         changes: { tag: { unchanged: "nerves" } },
         index: { from: 1}
      }
   }
}
```

Same changes but changes only: 

```javascript
{
   subject: { from: "subject", to: "new subject" },
   // body is unchanged
   embedded_author: {
      last_name: { from: "Doh", to: "Doe" }
   } 
   embedded_tags: {
      "tag-3": {
         op: "create", 
         changes: { tag: { to: "ash" }   }
         index: { to: 0 }
      },
      "tag-1": {
         op: "update",
         // no changes, only moved index
         index: { from: 0, to: 1 }
      },
      "tag-2": {
         op: "destroy",
         index: { from: 1}
      }
   }
}
```

**Comment by zachdaniel** [comment]
This will take some time to get right. One of the difficulties is that we're building a schema here that could ultimately need to change in the future which would be problematic. I'd also suggest potentially only storing the `to` here. The benefit of doing it this way is that any "stale" updates (i.e a an update action that uses an old version of a record that doesn't lock the record) won't affect the integrity of your log. We're going to be adding features to make stale updates not really an issue, but its something to keep in mind.

**Comment by frankdugan3** [comment]
Only *storing* the `to` field makes sense, but having the restore API return both `from` and `to` will make it much easier to implement a nice GUI for it. I have some hand-rolled stuff for this in my legacy code:

![2023-09-28T10:14:55,154175731-05:00](https://github.com/ash-project/ash_paper_trail/assets/10977914/2d270af3-ffdb-4633-8732-f761a05cbcbd)

**Comment by rgraff** [comment]
I understand now. That’s not really a concern for my use case. Things I’m
versioning rarely get writes. I think I’d be ok just warning against that.

I want these as audit logs. The fancy Postgres query won’t work for me.

**Comment by rgraff** [comment]
Breaking this into three issues:

- [ ] add a `change_tracking_mode :full_diff`that works like above
- [ ] add an `undo_changes_action :undo` option to create an action that will undo only the changes made in that version. The actual Change will be a module that can be manually added to a an action via a mixin.
- [ ] add an `restore_changes_action :restore` option to create an action that will restore all fields in the changes hash to their state at the time of versioning. The Change can also just be manually added to an action via a mixin.
- [ ] add a `lock_on_update: true` option to ensure integrating of the changes map if desired.
